# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc8a7055980e92eaffa1b6ce6c92a897a3af0ae4196203faedc0895d495dc1d53fe83843a57a0c48f5342fd7af8b7a2f9eb52d4924203bcaf1e5c74fbb453ee

test:
  secret_key_base: 1ff37547cf52ad4d8e8532efd6e981498eebaf9bb974f69c6389b5f4bccb4e42eaad6e224b20bd14998b9fc6b347d0903dfda6fd73aee0645541918cc1191d32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
